# Generated by Django 4.2.2 on 2023-07-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(default='initial', max_length=50)),
            ],
        ),
    ]
