# Generated by Django 4.2.2 on 2023-07-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0002_task_created_task_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
