# Generated by Django 4.2.2 on 2023-07-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0004_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_id',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50, null=True),
        ),
    ]
