# Generated by Django 4.2.2 on 2023-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stdweb", "0005_task_celery_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
