# Generated by Django 4.2.2 on 2023-07-07 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0006_alter_task_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
