# Generated by Django 4.2.6 on 2024-03-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0007_task_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('skyportal_upload', 'Can upload the task results to SkyPortal')]},
        ),
    ]
