# Generated by Django 4.2.6 on 2025-05-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0008_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
