# Generated by Django 4.2.6 on 2025-05-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0009_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='files',
            field=models.TextField(blank=True),
        ),
    ]
