# Generated by Django 5.1.6 on 2025-06-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0010_preset_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Initial config for the task, in JSON format'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='files',
            field=models.TextField(blank=True, help_text='Files to be copied into new task, one per line'),
        ),
    ]
