# Generated by Django 5.2.4 on 2025-08-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0010_preset_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('skyportal_upload', 'Can upload the task results to SkyPortal'), ('view_all_tasks', 'Can view tasks from all users')]},
        ),
        migrations.AlterField(
            model_name='preset',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Initial config for the task, in JSON format'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='files',
            field=models.TextField(blank=True, help_text='Files to be copied into new task, one per line'),
        ),
    ]
