# Generated by Django 5.2.4 on 2025-12-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0011_alter_task_options_alter_preset_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_chain_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
