# Generated by Django 5.2.4 on 2025-12-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0012_add_celery_chain_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_pid',
            field=models.IntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
