# Generated by Django 5.2.4 on 2025-12-31 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0013_task_celery_pid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('skyportal_upload', 'Can upload the task results to SkyPortal'), ('view_all_tasks', 'Can view tasks from all users'), ('edit_all_tasks', 'Can modify tasks from all users')]},
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('task_create', 'Task Created'), ('task_delete', 'Task Deleted'), ('task_duplicate', 'Task Duplicated'), ('task_update', 'Task Updated'), ('task_archive', 'Task Archived'), ('task_cleanup', 'Task Cleanup'), ('processing_start', 'Processing Started'), ('processing_complete', 'Processing Completed'), ('processing_failed', 'Processing Failed'), ('processing_cancel', 'Processing Cancelled'), ('file_upload', 'File Uploaded'), ('config_change', 'Config Changed')], db_index=True, max_length=50)),
                ('task_id_ref', models.IntegerField(blank=True, help_text='Preserved task ID after task deletion', null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stdweb.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='stdweb_acti_user_id_089047_idx'), models.Index(fields=['action', 'timestamp'], name='stdweb_acti_action_276713_idx')],
            },
        ),
    ]
