# Generated by Django 5.2.4 on 2026-01-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0014_alter_task_options_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='moc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
