# Generated by Django 6.0.1 on 2026-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stdweb', '0015_task_dec_task_moc_task_ra_task_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='auth.group'),
        ),
    ]
